# Generated by Django 3.2.3 on 2022-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='jogador',
            new_name='pelada',
        ),
        migrations.AlterField(
            model_name='pelada',
            name='quantidade_jogadores',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
