# Generated by Django 3.2.3 on 2022-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_jogador_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='tipo_jogador',
            field=models.CharField(choices=[('GOLEIRO', 'Goleiro'), ('ZAGUEIRO', 'Zagueiro'), ('MEIO CAMPO', 'Meio Campo'), ('ATACANTE', 'Atacante')], default='Zagueiro', max_length=15),
        ),
    ]
