# Generated by Django 3.2.3 on 2022-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_jogador_tipo_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelada',
            name='quantidade_jogadores',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Quantidade de jogadores na linha'),
        ),
    ]
