# Generated by Django 3.2.3 on 2022-12-08 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_jogador_estrelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('match_name', models.CharField(max_length=50)),
                ('number_players', models.IntegerField(blank=True, default=5, null=True, verbose_name='Number of players playing')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('stars', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('type_player', models.CharField(choices=[('GOALKEEPER', 'goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELD', 'Midfield'), ('STRIKER', 'Striker')], default='Defender', max_length=15)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.match')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Pelada',
        ),
    ]
